name: fake_news
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib==3.5.1
  - mlflow==1.24.0
  - networkx==2.7.1
  - numpy==1.21.2
  - pandas==1.4.1
  - PyYAML==6.0
  - scikit_learn==1.0.2
  - torch==1.11.0
  - torch_geometric==2.0.4
  - torch_scatter==2.0.9
  - pip:
    - seaborn==0.11.2
