## Use [] for hyper-parameter tuning
dataset: 'politifact'
early_stopping: 50
cuda: 'auto'
batch: 128
lr: 0.001
weight_decay: 0.01
epochs: 300
dropout: 0
pooling: 'global_max_pool'
gat_layer: 'GATConv'
hid_dims: [ [16 ] ]
readout_dim: 64
news_dim: 64
num_heads:  [6,7,8]
save_name: None
feature: 'content'

