## Use [] for hyper-parameter tuning
dataset: ['gossipcop']
early_stopping: 50
cuda: 'auto'
batch: 128
lr: 0.001
weight_decay: 0.01
epochs: 300
dropout: 0
pooling: 'global_attention_with_relu_linear'
gat_layer: 'GATConv'
hid_dims: [ [64,64] ]
readout_dim: 64
news_dim:  64
num_heads: 1
save_name: None
feature: 'content'

